d /var/lib/imac5k             0755 root   root   -
d /var/lib/imac5k/kernels     0755 root   root   -
d /var/lib/imac5k/notices     0755 root   root   -
d /var/cache/imac5k           0750 imac5k imac5k -
d /var/cache/imac5k/srpms     0750 imac5k imac5k -
d /var/cache/imac5k/work      0750 imac5k imac5k -
